name: flutter_application_dynamic
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  audioplayers: ^0.20.1
  path_provider: ^2.0.5
  responsive_builder: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/blueright.jpg
    - assets/images/games.json
    - assets/images/
    - assets/
    - assets/games/
    - assets/games/vowel-consonant/game.json 
    - assets/games/vowel-consonant/easy/
    - assets/games/vowel-consonant/easy/Vowel/
    - assets/games/vowel-consonant/easy/Consonant/
    - assets/games/vowel-consonant/easy/Vowel/Normal/
    - assets/games/vowel-consonant/easy/Consonant/Normal/
    - assets/games/vowel-consonant/easy/Vowel/Hint1/
    - assets/games/vowel-consonant/easy/Consonant/Hint1/
    - assets/games/vowel-consonant/easy/Vowel/Hint2/
    - assets/games/vowel-consonant/easy/Consonant/Hint2/
    - assets/games/vowel-consonant/hard/
    - assets/games/vowel-consonant/hard/Vowel/
    - assets/games/vowel-consonant/hard/Consonant/
    - assets/games/vowel-consonant/hard/Vowel/Normal/
    - assets/games/vowel-consonant/hard/Consonant/Normal/
    - assets/games/vowel-consonant/hard/Vowel/Hint1/
    - assets/games/vowel-consonant/hard/Consonant/Hint1/
    - assets/games/vowel-consonant/hard/Vowel/Hint2/
    - assets/games/vowel-consonant/hard/Consonant/Hint2/
    - assets/games/numbers/
    - assets/games/numbers/hard/10/Normal/
    - assets/games/numbers/hard/10/Hint1/
    - assets/games/numbers/hard/10/Hint2/
    - assets/games/numbers/hard/11/Normal/
    - assets/games/numbers/hard/11/Hint1/
    - assets/games/numbers/hard/11/Hint2/
    - assets/games/numbers/hard/12/Normal/
    - assets/games/numbers/hard/12/Hint1/
    - assets/games/numbers/hard/12/Hint2/
    - assets/games/numbers/hard/13/Normal/
    - assets/games/numbers/hard/13/Hint1/
    - assets/games/numbers/hard/13/Hint2/
    - assets/games/numbers/hard/14/Normal/
    - assets/games/numbers/hard/14/Hint1/
    - assets/games/numbers/hard/14/Hint2/
    - assets/games/numbers/hard/15/Normal/
    - assets/games/numbers/hard/15/Hint1/
    - assets/games/numbers/hard/15/Hint2/
    - assets/games/numbers/hard/16/Normal/
    - assets/games/numbers/hard/16/Hint1/
    - assets/games/numbers/hard/16/Hint2/
    - assets/games/numbers/hard/17/Normal/
    - assets/games/numbers/hard/17/Hint1/
    - assets/games/numbers/hard/17/Hint2/
    - assets/games/numbers/hard/18/Normal/
    - assets/games/numbers/hard/18/Hint1/
    - assets/games/numbers/hard/18/Hint2/
    - assets/games/numbers/hard/19/Normal/
    - assets/games/numbers/hard/19/Hint1/
    - assets/games/numbers/hard/19/Hint2/
    - assets/games/numbers/easy/0/Normal/
    - assets/games/numbers/easy/0/Hint1/
    - assets/games/numbers/easy/0/Hint2/
    - assets/games/numbers/easy/1/Normal/
    - assets/games/numbers/easy/1/Hint1/
    - assets/games/numbers/easy/1/Hint2/
    - assets/games/numbers/easy/2/Normal/
    - assets/games/numbers/easy/2/Hint1/
    - assets/games/numbers/easy/2/Hint2/
    - assets/games/numbers/easy/3/Normal/
    - assets/games/numbers/easy/3/Hint1/
    - assets/games/numbers/easy/3/Hint2/
    - assets/games/numbers/easy/4/Normal/
    - assets/games/numbers/easy/4/Hint1/
    - assets/games/numbers/easy/4/Hint2/
    - assets/games/numbers/easy/5/Normal/
    - assets/games/numbers/easy/5/Hint1/
    - assets/games/numbers/easy/5/Hint2/
    - assets/games/numbers/easy/6/Normal/
    - assets/games/numbers/easy/6/Hint1/
    - assets/games/numbers/easy/6/Hint2/
    - assets/games/numbers/easy/7/Normal/
    - assets/games/numbers/easy/7/Hint1/
    - assets/games/numbers/easy/7/Hint2/
    - assets/games/numbers/easy/8/Normal/
    - assets/games/numbers/easy/8/Hint1/
    - assets/games/numbers/easy/8/Hint2/
    - assets/games/numbers/easy/9/Normal/
    - assets/games/numbers/easy/9/Hint1/
    - assets/games/numbers/easy/9/Hint2/

