name: flutter_application_dynamic
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  audioplayers: ^0.20.1
  path_provider: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/games/vowel-consonant/easy/Vowel/Hint2/
    - assets/images/blueright.jpg
    - assets/images/games.json
    - assets/images/
    - assets/
    - assets/games/vowel-consonant/game.json 
    - assets/games/vowel-consonant/easy/
    - assets/games/vowel-consonant/easy/Vowel/
    - assets/games/vowel-consonant/easy/Consonant/
    - assets/games/vowel-consonant/easy/Vowel/Normal/
    - assets/games/vowel-consonant/easy/Consonant/Normal/
    - assets/games/vowel-consonant/easy/Vowel/Hint1/
    - assets/games/vowel-consonant/easy/Consonant/Hint1/
    - assets/games/vowel-consonant/easy/Vowel/Hint2/
    - assets/games/vowel-consonant/easy/Consonant/Hint2/
    - assets/games/vowel-consonant/hard/
    - assets/games/vowel-consonant/hard/Vowel/
    - assets/games/vowel-consonant/hard/Consonant/
    - assets/games/vowel-consonant/hard/Vowel/Normal/
    - assets/games/vowel-consonant/hard/Consonant/Normal/
    - assets/games/vowel-consonant/hard/Vowel/Hint1/
    - assets/games/vowel-consonant/hard/Consonant/Hint1/
    - assets/games/vowel-consonant/hard/Vowel/Hint2/
    - assets/games/vowel-consonant/hard/Consonant/Hint2/
    - assets/games/

